[package]
name = "gol"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
braille = "1.0.3"
rand = "0.8.5"
termwiz = "0.20.0"
